name: Latest SAP Ariba Extensibility blog posts in SAP Community workflow
on:
  schedule:
    # Runs every day at 18:05
    - cron: '5 18 * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts related to SAP Ariba Extensibility in SAP Community
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "SAP-COMMUNITY-ARIBA-EXTENSIBILITY"
          accept_header: "*/*"
          feed_list: "https://content.services.sap.com/feed?type=blogpost&tags=ff06b2d6-8e62-4ba2-b1a8-9d4867d0a62f&title=Latest%20blog%20posts%20for%20SAP%20Ariba%20Extensibility"
